### ISSUE TITLE
Reload broken in production: sockjs/info

### ISSUE THREAD

**Issue by dweldon** [maxkferg/meteor-cdn#1]
Hey this is a really helpful package! Unfortunately, when I use it in production, my apps don't reload after an update. Right after the update, it looks like the client makes a `GET` request like:

`GET https://d3v9orfbcuudtl.cloudfront.net/sockjs/info?cb=i5412at9sw`

Which then throws a `No 'Access-Control-Allow-Origin'` error and breaks the reload process. Any ideas?

**Comment by maxkferg** [comment]
Thanks for reporting this. I think this is a bug introduced in the last update. The client is trying to fetch sockjs info from CDN (it should definitely not do this). I'll look into it more tomorrow.

**Comment by dweldon** [comment]
Thanks Max - let me know what you find. I'd like to feature this package on my blog once I get everything running smoothly in production.

**Comment by maxkferg** [comment]
@dweldon. I made some pretty extensive changes to the way that this package handles urls on the client side. We decided to move the package to https://github.com/NitroLabs/meteor-cdn. The reload issue should no longer occur as of nitrolabs:cdn@1.2.0. 

For future reference: Make sure that the HOST header is reaching the Meteor server (you will see a warning in the server logs if it doesn't). CloudFront, and some of the other CDN services, remove the HOST header to try and improve caching, but this can cause some annoying problems

**Comment by dweldon** [comment]
Well I gave `nitrolabs:cdn` a try and I just got 404 errors with meteor `1.2.1` and a CF config that looks something like:

```
Origin Domain Name: appname.example.com
Origin ID: appname.example.com
Origin Protocol Policy: HTTPS Only
Viewer Protocol Policy: HTTPS Only
Forward Headers: Whitelist
  Host
Forward Query Strings: yes
Compress Objects Automatically: yes
Price Class: US and Europe
```

I'm uncertain how to debug this further. One possible complexity is that I have nginx in front of my app... though that didn't seem to break `maxkferg:cdn`. If you have any ideas, let me now.

**Comment by maxkferg** [comment]
Your CF config looks good. nitrolabs:cdn only contains a few modifications on the server side, so I am surprised that you are getting 404 errors.
Have a look at line 106 in https://github.com/NitroLabs/meteor-cdn/blob/master/lib/server.js:

``` js
var isFromCDN = (req.headers.host===cdn.host && req.headers.host!==root.host);
```

Do you have access to the server logs from your production server? I would be interested in any log messages from this package. In particular I need to know if the "Static File Not Found" or "Static resource not found: " is in the Meteor logs.

Regarding debugging: download a zip file of the nitrolabs:cdn and put it in your packages directory.
Put some console.log statements at line 106 to find the values of:
- isFromCDN
- pathname
- WebAppInternals.staticFiles
